// Auto-generated by hdf5_to_replay.py on 2026-05-13 17:08:32
// Source: updated010_20260214_204204.hdf5
// DO NOT EDIT — re-run hdf5_to_replay.py to regenerate

#pragma once
#include <stdint.h>

#define REPLAY_NUM_SAMPLES  75564
#define REPLAY_NUM_CHANNELS 4

extern const uint16_t replay_samples[REPLAY_NUM_SAMPLES][REPLAY_NUM_CHANNELS];
