// Auto-generated by train_mlp_tflite.py — do not edit
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char g_model[];
extern const int g_model_len;

#ifdef __cplusplus
}
#endif
