"""
Converts HDF5 Session into uint16_t c array for flash replay of raw emg signals

Example InvocationL: [Insert Example Invocation]

Output files:
EMG_Arm/src/drivers/replay_data.h - declares const array
EMG_Arm/src/drivers/replay_data.c - actual c array
"""

import h5py
import numpy as np
import argparse
from pathlib import Path
from datetime import datetime

parser = argparse.ArgumentParser(description="Convert HDF5 EMG Session to uint16_t C array")
parser.add_argument("--session", required=False, type=str, help="HDF5 filename", default="updated010_20260214_204204.hdf5")
parser.add_argument("--input-dir", required=False, type=str, help="HDF5 filename in input dir", default=Path("collected_data"))
parser.add_argument("--output-dir", required=False, type=str, help="HDF5 filename in output dir", default=Path("EMG_Arm/src/drivers"))
args = parser.parse_args()

hdf5_path = Path(args.input_dir) / args.session

if not hdf5_path.exists():
    print(f"[hdf5_to_replay] ERROR: file not found: {hdf5_path}")
    exit(1)

with h5py.File(hdf5_path, "r") as f:
    if "raw_samples/channels" not in f:
        print("[hdf5_to_replay] ERROR: missing dataset raw_samples/channels")
        exit(1)
    if "raw_samples/timestamps" not in f:
        print("[hdf5_to_replay] ERROR: missing dataset raw_samples/timestamps")
        exit(1)

    print(f"[hdf5_to_replay] Opened: {args.session}")
    print(f"[hdf5_to_replay] raw_samples shape: {f['raw_samples/channels'].shape}")

    channels = f["raw_samples/channels"][:]

if channels.shape[1] != 4:
    print("[hdf5_to_replay] ERROR: incorrect number of channels")
    exit(1)

print(f"[hdf5_to_replay] Samples: {channels.shape[0]}")
print(f"[hdf5_to_replay] Duration (s): {channels.shape[0]/1000}")
print(f"[hdf5_to_replay] Value Range: {channels.min()} - {channels.max()}")

samples = np.clip(channels, 0, 65535).round().astype(np.uint16)
print(f"[hdf5_to_replay] Cast complete: dtype={samples.dtype}, range=[{samples.min()}, {samples.max()}]")

header_path = Path(args.output_dir) / "replay_data.h"

n_samples = samples.shape[0]
n_channels = samples.shape[1]
timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

header_content = f"""// Auto-generated by hdf5_to_replay.py on {timestamp}
// Source: {args.session}
// DO NOT EDIT: re-run hdf5_to_replay.py to regenerate

#pragma once
#include <stdint.h>

#define REPLAY_NUM_SAMPLES  {n_samples}
#define REPLAY_NUM_CHANNELS {n_channels}

extern const uint16_t replay_samples[REPLAY_NUM_SAMPLES][REPLAY_NUM_CHANNELS];
"""

header_path.write_text(header_content)
print(f"[hdf5_to_replay] Wrote {header_path}")

source_path = Path(args.output_dir) / "replay_data.c"

SAMPLES_PER_LINE = 16

with open(source_path, "w") as out:
    out.write(f"// Auto-generated by hdf5_to_replay.py on {timestamp}\n")
    out.write(f"// Source: {args.session}\n")
    out.write("// DO NOT EDIT: re-run hdf5_to_replay.py to regenerate\n\n")
    out.write('#include "replay_data.h"\n\n')
    out.write(f"const uint16_t replay_samples[REPLAY_NUM_SAMPLES][REPLAY_NUM_CHANNELS] = {{\n")

    for i in range(0, n_samples, SAMPLES_PER_LINE):
        chunk = samples[i : i + SAMPLES_PER_LINE]
        for row in chunk:
            out.write(f"    {{{row[0]}, {row[1]}, {row[2]}, {row[3]}}},\n")

    out.write("};\n")

print(f"[hdf5_to_replay] Wrote {source_path}")

size_mb = source_path.stat().st_size / (1024 * 1024)
print(f"[hdf5_to_replay] File size: {size_mb:.1f} MB")